name: Go

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    -  name: Set up Cloud SDK
       uses: google-github-actions/setup-gcloud@v0.2.0
       with:
         project_id: ${{ secrets.gcp_project }}
         service_account_key: ${{ secrets.gcp_credentials }}
         export_default_credentials: true

    - name: Run
      run: go run main.go
      env:
          YLC_API_KEY: ${{ secrets.YLC_API_KEY }}
          YLC_CHANNEL_ID: ${{ secrets.YLC_CHANNEL_ID }}
          YLC_CALENDAR_ID: ${{ secrets.YLC_CALENDAR_ID }}

